services:
  init:
    image: alpinelinux/docker-cli:latest-aarch64
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        wget -O /config/15-mailboxes.conf https://apps.univrs.cloud/docker-mailserver/config/15-mailboxes.conf; \
        wget -O /config/postfix-main.cf https://apps.univrs.cloud/docker-mailserver/config/postfix-main.cf; \
        wget -O /config/fail2ban-jail.cf https://apps.univrs.cloud/docker-mailserver/config/fail2ban-jail.cf; \
        wget -O /config/rspamd/custom-commands.conf https://apps.univrs.cloud/docker-mailserver/config/rspamd-custom-commands.conf; \
        touch /config/.init_complete; \
        sleep 10; \
        rm -f /config/.init_complete; \
        docker rm -f $(hostname)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /messier/apps/mailserver/config:/config
    networks:
      - virgo
    restart: "no"
    healthcheck:
      test: "[ -f /config/.init_complete ]"
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 1s

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:15
    hostname: mail
    domainname: ${MX_DOMAIN}
    environment:
      - PUID=1000
      - PGID=100
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mail.${MX_DOMAIN}
      - POSTMASTER_ADDRESS=postmaster@${MX_DOMAIN}
      - POSTFIX_INET_PROTOCOLS=ipv4
      - POSTFIX_MAILBOX_SIZE_LIMIT=32212254720
      - POSTFIX_MESSAGE_SIZE_LIMIT=26214400
      - ENABLE_MTA_STS=1
      - ENABLE_MANAGESIEVE=1
      - SPOOF_PROTECTION=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_CLAMAV=1
      - ENABLE_SPF=1
      - ENABLE_RSPAMD=1
      - RSPAMD_LEARN=1
      - RSPAMD_GREYLISTING=1
      - MOVE_SPAM_TO_JUNK=1
      - ENABLE_POSTGREY=0
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_SRS=1
    volumes:
      - /messier/apps/traefik/letsencrypt/acme.json:/etc/letsencrypt/acme.json:ro
      - /messier/apps/mailserver/config/15-mailboxes.conf:/etc/dovecot/conf.d/15-mailboxes.conf:ro
      - /messier/apps/mailserver/data:/var/mail
      - /messier/apps/mailserver/state:/var/mail-state
      - /messier/apps/mailserver/logs:/var/log/mail
      - /messier/apps/mailserver/config:/tmp/docker-mailserver
    labels:
      - "traefik.enable=true"
      - "traefik.docker.allowNonRunning=true"
      - "traefik.http.routers.mail-cert.rule=Host(`mail.${MX_DOMAIN}`)"
      - "traefik.http.routers.mail-cert.entrypoints=https"
      - "traefik.http.routers.mail-cert.tls.certresolver=${CERTRESOLVER:+${CERTRESOLVER}}"
      - "traefik.http.routers.mail-cert.service=noop@internal"
      - "traefik.http.routers.mail-cert.middlewares=secure-headers@file"
      - "traefik.http.services.rspamd.loadbalancer.server.port=11334"
      - "traefik.http.routers.rspamd.service=rspamd"
      - "traefik.http.routers.rspamd.rule=Host(`rspamd.${DOMAIN}`)"
      - "traefik.http.routers.rspamd.entrypoints=https"
      - "traefik.http.routers.rspamd.tls.certresolver=${CERTRESOLVER:+${CERTRESOLVER}}"
      - "traefik.http.routers.rspamd.middlewares=secure-headers@file,authelia@file"
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "4190:4190"
    networks:
      - virgo
    depends_on:
      init:
        condition: service_healthy
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 3

  autodiscover:
    image: ghcr.io/univrs-cloud/autodiscover-email-settings:latest
    environment:
      - COMPANY_NAME=${MX_DOMAIN}
      - SUPPORT_URL=https://autodiscover.${MX_DOMAIN}
      - PROFILE_IDENTIFIER=${MX_DOMAIN}.autodiscover
      - DOMAIN=${MX_DOMAIN}
      - IMAP_HOST=mail.${MX_DOMAIN}
      - IMAP_PORT=993
      - IMAP_SOCKET=SSL
      - SMTP_HOST=mail.${MX_DOMAIN}
      - SMTP_PORT=465
      - SMTP_SOCKET=SSL
    labels:
      - "traefik.enable=true"
      - "traefik.docker.allowNonRunning=true"
      - "traefik.http.services.autodiscover.loadbalancer.server.port=8000"
      # Thunderbird / Apple Mail
      - "traefik.http.routers.autoconfig.service=autodiscover"
      - "traefik.http.routers.autoconfig.rule=Host(`autoconfig.${MX_DOMAIN}`)"
      - "traefik.http.routers.autoconfig.entrypoints=https"
      - "traefik.http.routers.autoconfig.tls.certresolver=${CERTRESOLVER:+${CERTRESOLVER}}"
      - "traefik.http.routers.autoconfig.middlewares=secure-headers@file"
      # Outlook
      - "traefik.http.routers.autodiscover.service=autodiscover"
      - "traefik.http.routers.autodiscover.rule=Host(`autodiscover.${MX_DOMAIN}`)"
      - "traefik.http.routers.autodiscover.entrypoints=https"
      - "traefik.http.routers.autodiscover.tls.certresolver=${CERTRESOLVER:+${CERTRESOLVER}}"
      - "traefik.http.routers.autodiscover.middlewares=secure-headers@file"
    networks:
      - virgo
    restart: always

networks:
  virgo:
    external: true
