mail_plugins {
  fts = yes
  fts_flatcurve = yes
}

fts_autoindex = yes
fts_search_read_fallback = yes

mailbox Trash {
  special_use = \Trash
  fts_autoindex = no
}

mailbox Junk {
  special_use = \Junk
  fts_autoindex = no
}

language en {
  default = yes
  language_filters = normalizer-icu snowball english-possessive stopwords
}

language_filters = normalizer-icu snowball stopwords
language_tokenizers = generic email-address
language_tokenizer_generic_algorithm = simple

fts flatcurve {
  substring_search = yes
}

service indexer-worker {
  vsz_limit = 1G
}
