# yamllint disable rule:comments-indentation
---
#administration:
#  enable: true
#  enable_ui: true
#  users:
#    - 'voyager'
#  groups:
#    - 'admins'

access_control:
  rules:
  - domain: "auth.{{ env `DOMAIN` }}" #this should be your authentication URL
    policy: "bypass"
  - domain: ["*.{{ env `DOMAIN` }}", "{{ env `DOMAIN` }}"]
    policy: "bypass"
    networks:
      - "192.168.0.0/16" #bypass if connected on local network
      - "10.6.0.0/16" #bypass if connected over VPN

session:
  cookies:
  - domain: "{{ env `DOMAIN` }}" #should match whatever your root protected domain is
    authelia_url: "https://auth.{{ env `DOMAIN` }}"
...
