# yamllint disable rule:comments-indentation
---
#administration:
#  enable: true
#  enable_ui: true
#  users:
#    - 'robert'
#  groups:
#    - 'admins'

access_control:
  rules:
  - domain: "auth.somewhere.univrs.cloud" #this should be your authentication URL
    policy: "bypass"
  - domain: ["*.somewhere.univrs.cloud", "somewhere.univrs.cloud"]
    policy: "bypass"
    networks:
      - "192.168.0.0/16" #bypass if connected on local network
      - "10.6.0.0/16" #bypass if connected over VPN

session:
  cookies:
  - domain: "somewhere.univrs.cloud" #should match whatever your root protected domain is
    authelia_url: "https://auth.somewhere.univrs.cloud"
...
