services:
  authelia-init-secrets:
    image: alpine
    container_name: authelia-init-secrets
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mkdir -p /config/assets; \
        mkdir -p /secrets; \
        [ -f /secrets/jwt_secret ] || head -c 64 /dev/urandom | base64 | tr -d "\n" > /secrets/jwt_secret; \
        [ -f /secrets/session_secret ] || head -c 64 /dev/urandom | base64 | tr -d "\n" > /secrets/session_secret; \
        [ -f /secrets/storage_key ] || head -c 64 /dev/urandom | base64 | tr -d "\n" > /secrets/storage_key; \
        echo 'Secrets initialized.'
    volumes:
      - /messier/apps/authelia/config:/config
      - /messier/apps/authelia/secrets:/secrets
    networks:
      virgo:
    restart: no

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    environment:
      - PUID=1000
      - PGID=100
      - AUTHELIA_THEME=light
      - AUTHELIA_SERVER_ADDRESS=tcp://0.0.0.0:9091/
      - AUTHELIA_SERVER_ASSET_PATH=/config/assets/
      - AUTHELIA_SERVER_BUFFERS_WRITE=8192
      - AUTHELIA_SERVER_BUFFERS_READ=8192
      - AUTHELIA_SERVER_DISABLE_HEALTHCHECK=false
      - AUTHELIA_SERVER_ENDPOINTS_ENABLE_EXPVARS=false
      - AUTHELIA_SERVER_ENDPOINTS_ENABLE_PPROF=false
      - AUTHELIA_LOG_LEVEL=info
      - AUTHELIA_LOG_KEEP_STDOUT=false
      - AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_RESET_DISABLE=true
      - AUTHELIA_AUTHENTICATION_BACKEND_REFRESH_INTERVAL=5m
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH=/config/users.yml
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_WATCH=true
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_ALGORITHM=bcrypt
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_BCRYPT_VARIANT=standard
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_BCRYPT_COST=12
      - AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY=one_factor
      - AUTHELIA_SESSION_NAME=virgoOS
      - AUTHELIA_SESSION_REDIS_HOST=authelia-redis
      - AUTHELIA_SESSION_REDIS_PORT=6379
      - AUTHELIA_REGULATION_MAX_RETRIES=3
      - AUTHELIA_REGULATION_FIND_TIME=10m
      - AUTHELIA_REGULATION_BAN_TIME=12h
      - AUTHELIA_STORAGE_LOCAL_PATH=/config/db.sqlite3
      - AUTHELIA_NOTIFIER_DISABLE_STARTUP_CHECK=true
      - AUTHELIA_NOTIFIER_FILESYSTEM_FILENAME=/config/notification.txt
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/secrets/session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/storage_key
    volumes:
      - /messier/apps/authelia/config:/config
      - /messier/apps/authelia/secrets:/secrets:ro
    labels:
      - "traefik.enable=true"
      # Define the Authelia service
      - "traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN}`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=le"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      # Define the Authelia middleware for other services to use
      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.${DOMAIN}"
      - "traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
    networks:
      virgo:
    depends_on:
      - authelia-init-secrets
      - authelia-redis
    restart: unless-stopped

  authelia-redis:
    image: redis:latest
    container_name: authelia-redis
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no", "--maxmemory", "32mb", "--maxmemory-policy", "allkeys-lru"]
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /messier/apps/authelia/redis:/data
    networks:
      virgo:
    restart: unless-stopped

networks:
  virgo:
    external: true
