services:
  authelia-init:
    image: alpinelinux/docker-cli:latest-aarch64
    container_name: authelia-init
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        [ -f /config/configuration.yml ] || wget -O /config/configuration.yml https://apps.univrs.cloud/authelia/config/configuration.yml; \
        [ -f /config/users.yml ] || wget -O /config/users.yml https://apps.univrs.cloud/authelia/config/users.yml; \
        mkdir -p /config/assets/locales/en; \
        wget -O /config/assets/logo.png https://apps.univrs.cloud/authelia/config/assets/logo.png; \
        wget -O /config/assets/favicon.ico https://apps.univrs.cloud/authelia/config/assets/favicon.ico; \
        wget -O /config/assets/locales/en/portal.json https://apps.univrs.cloud/authelia/config/assets/locales/en/portal.json; \
        mkdir -p /secrets; \
        [ -f /secrets/jwt_secret ] || head -c 64 /dev/urandom | base64 | tr -d "\n" > /secrets/jwt_secret; \
        [ -f /secrets/session_secret ] || head -c 64 /dev/urandom | base64 | tr -d "\n" > /secrets/session_secret; \
        [ -f /secrets/storage_key ] || head -c 64 /dev/urandom | base64 | tr -d "\n" > /secrets/storage_key; \
        touch /config/.init_complete; \
        sleep 10; \
        rm -f /config/.init_complete; \
        docker rm -f $(hostname)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /messier/apps/authelia/config:/config
      - /messier/apps/authelia/secrets:/secrets
    networks:
      - virgo
    restart: no
    healthcheck:
      test: "[ -f /config/.init_complete ]"
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 1s

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    environment:
      - PUID=1000
      - PGID=100
      - DOMAIN=${DOMAIN}
      - X_AUTHELIA_CONFIG_FILTERS=template
      - AUTHELIA_THEME=light
      - AUTHELIA_SESSION_SECRET_FILE=/secrets/session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/storage_key
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/jwt_secret
      - AUTHELIA_SERVER_ADDRESS=tcp://0.0.0.0:9091/
      - AUTHELIA_SERVER_ASSET_PATH=/config/assets/
      - AUTHELIA_SERVER_BUFFERS_WRITE=8192
      - AUTHELIA_SERVER_BUFFERS_READ=8192
      - AUTHELIA_SERVER_DISABLE_HEALTHCHECK=false
      - AUTHELIA_SERVER_ENDPOINTS_ENABLE_EXPVARS=false
      - AUTHELIA_SERVER_ENDPOINTS_ENABLE_PPROF=false
      - AUTHELIA_LOG_LEVEL=info
      - AUTHELIA_LOG_KEEP_STDOUT=false
      - AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_RESET_DISABLE=true
      - AUTHELIA_AUTHENTICATION_BACKEND_REFRESH_INTERVAL=5m
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH=/config/users.yml
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_WATCH=true
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_ALGORITHM=bcrypt
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_BCRYPT_VARIANT=standard
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_BCRYPT_COST=12
      - AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY=one_factor
      - AUTHELIA_SESSION_NAME=virgoOS
      - AUTHELIA_SESSION_REDIS_HOST=authelia-redis
      - AUTHELIA_SESSION_REDIS_PORT=6379
      - AUTHELIA_REGULATION_MODES=ip
      - AUTHELIA_REGULATION_MAX_RETRIES=3
      - AUTHELIA_REGULATION_FIND_TIME=10m
      - AUTHELIA_REGULATION_BAN_TIME=12h
      - AUTHELIA_STORAGE_LOCAL_PATH=/config/db.sqlite3
      - AUTHELIA_NOTIFIER_DISABLE_STARTUP_CHECK=true
      - AUTHELIA_NOTIFIER_FILESYSTEM_FILENAME=/config/notification.txt
    volumes:
      - /messier/apps/authelia/config:/config
      - /messier/apps/authelia/secrets:/secrets
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=virgo"
      - "traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN}`)"
      - "traefik.http.routers.authelia.entrypoints=https"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=${CERTRESOLVER:+${CERTRESOLVER}}"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
    networks:
      - internal
      - virgo
    depends_on:
      authelia-init:
        condition: service_healthy
      authelia-redis:
        condition: service_started
    restart: always

  authelia-redis:
    image: redis:latest
    container_name: authelia-redis
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /messier/apps/authelia/redis:/data
    networks:
      - internal
    restart: always

networks:
  internal:
  virgo:
    external: true
