services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - PUID=1000
      - PGID=100
      - PASSWORD_HASH=${PASSWORD_HASH}
      - WG_HOST=vpn.${DOMAIN}
      - WG_DEFAULT_ADDRESS=${DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${DEFAULT_DNS}
      - WG_ALLOWED_IPS=${ALLOWED_IPS}
    volumes:
      - /messier/apps/wg-easy:/etc/wireguard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.rule=Host(`vpn.${DOMAIN}`)"
      - "traefik.http.routers.wireguard.entrypoints=https"
      - "traefik.http.routers.wireguard.tls=true"
      - "traefik.http.routers.wireguard.tls.certresolver=${CERTRESOLVER:+${CERTRESOLVER}}"
      - "traefik.http.routers.wireguard.service=wireguard"
      - "traefik.http.routers.wireguard.middlewares=secure-headers@docker,authelia@docker"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
    ports:
      - "51820:51820/udp"
    networks:
      - virgo
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

networks:
  virgo:
    external: true
