services:
  stalwart-mail:
    image: stalwartlabs/mail-server:latest
    container_name: stalwart-mail
    volumes:
      - /messier/apps/traefik/certdump/mail.univrs.cloud:/opt/stalwart-mail/certs:ro
      - /messier/apps/stalwart-mail:/opt/stalwart-mail
    labels:
      - "traefik.enable=true"
      # Web Admin Interface & JMAP API - using the same domain for all services
      - "traefik.http.routers.stalwart-web.rule=Host(`mail.${DOMAIN}`)"
      - "traefik.http.routers.stalwart-web.entrypoints=https"
      - "traefik.http.routers.stalwart-web.tls=true"
      - "traefik.http.routers.stalwart-web.tls.certresolver=${CERTRESOLVER:+${CERTRESOLVER}}"
      - "traefik.http.routers.stalwart-web.service=stalwart-web"
      - "traefik.http.routers.stalwart-web.middlewares=secure-headers@docker"
      - "traefik.http.services.stalwart-web.loadbalancer.server.port=8080"
    ports:
      - "25:25/tcp" # SMTP
      - "465:465/tcp" # SMTP
      - "587:587/tcp" # SMTP
      - "993:993/tcp" # IMAP
    networks:
      - virgo
    restart: unless-stopped

networks:
  virgo:
    external: true
