http:
  routers:
    localservice:
      rule: "Host(`{{ env `DOMAIN` }}`)"
      entryPoints:
        - "https"
      service: "localservice"
      tls: {{ if ne (env `CERTRESOLVER`) "" }}
        certResolver: "{{ env `CERTRESOLVER` }}"
      {{ else }}
        {}
      {{ end }}
      middlewares:
        - "secure-headers@docker"
        - "authelia@docker"

  services:
    localservice:
      loadBalancer:
        servers:
          - url: "https://172.17.0.1:3000"
        serversTransport: "insecure-transport@file"
