http:
  routers:
    localservice:
      rule: "Host(`{{ env `DOMAIN` }}`)"
      entryPoints:
        - "https"
      service: "localservice"
      tls: {{ if eq (env `CERTRESOLVER`) "ledns" }}
        certResolver: "ledns"
        domains:
          - main: "*.{{ join `.` (rest (splitList `.` (env `DOMAIN`))) }}"
          - main: "*.{{ env `DOMAIN` }}"
      {{ else if ne (env `CERTRESOLVER`) "" }}
        certResolver: "{{ env `CERTRESOLVER` }}"
      {{ else }}
        {}
      {{ end }}
      middlewares:
        - "secure-headers@file"
    misdirected:
      rule: "PathPrefix(`/`)"
      priority: 1
      entryPoints:
        - "https"
      service: "localservice"
      tls: {}
      middlewares:
        - "misdirected"

  middlewares:
    misdirected:
      addPrefix:
        prefix: "/__misdirected"

  services:
    localservice:
      loadBalancer:
        servers:
          - url: "https://172.30.0.1:3000"
        serversTransport: "insecure-transport@file"
