http:
  routers:
    localservice:
      rule: "Host(`{{ env `DOMAIN` }}`)"
      entryPoints:
        - "https"
      service: "localservice"
      tls: {{ if eq (env `CERTRESOLVER`) "ledns" }}
        certResolver: "ledns"
        domains:
          - main: "{{ env `DOMAIN` }}"
            sans:
              - "*.{{ env `DOMAIN` }}"
      {{ else if ne (env `CERTRESOLVER`) "" }}
        certResolver: "{{ env `CERTRESOLVER` }}"
      {{ else }}
        {}
      {{ end }}
      middlewares:
        - "secure-headers@file"

    dashboard:
      rule: "Host(`traefik.{{ env `DOMAIN` }}`)"
      entryPoints:
        - "https"
      service: "api@internal"
      tls: {{ if or (eq (env `CERTRESOLVER`) "") (eq (env `CERTRESOLVER`) "ledns") }}
        {}
      {{ else }}
        certResolver: "{{ env `CERTRESOLVER` }}"
      {{ end }}
      middlewares:
        - "secure-headers@file"
        - "authelia@file"

  services:
    localservice:
      loadBalancer:
        servers:
          - url: "https://172.30.0.1:3000"
        serversTransport: "insecure-transport@file"
