http:
  serversTransports:
    insecure-transport:
      insecureSkipVerify: true
  middlewares:
    default-ratelimit:
      rateLimit:
        average: 1000
        burst: 2000
        period: 1s
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    secure-headers:
      chain:
        middlewares:
          - "security-headers"
          - "embed-headers"
          - "embed-csp"
    security-headers:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        contentTypeNosniff: true
        browserXssFilter: true
        customRequestHeaders:
          x-forwarded-proto: https
        customResponseHeaders:
          server: ""
          x-powered-by: ""
    embed-headers:
      headers:
        customResponseHeaders:
          x-frame-options: ""
    embed-csp:
      plugin:
        rewriteheaders:
          rewrites:
            - header: "Content-Security-Policy"
              regex: "frame-ancestors[^;]*;?"
              replacement: ""
            - header: "Content-Security-Policy"
              regex: "$"
              replacement: "; frame-ancestors 'self' https://{{ env `DOMAIN` }}"
              fallback: "frame-ancestors 'self' https://{{ env `DOMAIN` }}"
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/authz/forward-auth?authelia_url=https%3A%2F%2F{{ env `DOMAIN` }}%2Flogin"
        trustForwardHeader: true
        authResponseHeaders: "Remote-User,Remote-Groups,Remote-Name,Remote-Email"

tls:
  options:
    default:
      minVersion: VersionTLS13
