services:
  authelia-init-secrets:
    image: alpine
    container_name: authelia-init-secrets
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    command: >
      "mkdir -p /secrets &&
      [ -f /secrets/jwt_secret ] || head -c 64 /dev/urandom | base64 > /secrets/jwt_secret &&
      [ -f /secrets/session_secret ] || head -c 64 /dev/urandom | base64 > /secrets/session_secret &&
      [ -f /secrets/storage_key ] || head -c 64 /dev/urandom | base64 > /secrets/storage_key &&
      [ -f /secrets/smtp_password ] || echo \"$SMTP_PASSWORD\" > /secrets/smtp_password &&
      echo 'Secrets initialized.'"
    volumes:
      - /messier/apps/authelia/secrets:/secrets
    restart: no

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    environment:
      - PUID=1000
      - PGID=100
      - AUTHELIA_THEME=light
      - AUTHELIA_SERVER_ADDRESS=tcp://0.0.0.0:9091/
      - AUTHELIA_SERVER_ASSET_PATH=/config/assets/
      - AUTHELIA_SERVER_BUFFERS_WRITE=8192
      - AUTHELIA_SERVER_BUFFERS_READ=8192
      - AUTHELIA_SERVER_DISABLE_HEALTHCHECK=false
      - AUTHELIA_SERVER_ENDPOINTS_ENABLE_EXPVARS=false
      - AUTHELIA_SERVER_ENDPOINTS_ENABLE_PPROF=false
      - AUTHELIA_LOG_LEVEL=info
      - AUTHELIA_LOG_KEEP_STDOUT=false
      - AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_RESET_DISABLE=false
      - AUTHELIA_AUTHENTICATION_BACKEND_REFRESH_INTERVAL=5m
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH=/config/users.yml
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_WATCH=true
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_ALGORITHM=bcrypt
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_BCRYPT_VARIANT=standard
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_BCRYPT_COST=12
      - AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY=one_factor
      - AUTHELIA_SESSION_NAME=virgoOS
      - AUTHELIA_SESSION_REDIS_HOST=authelia-redis
      - AUTHELIA_SESSION_REDIS_PORT=6379
      - AUTHELIA_REGULATION_MAX_RETRIES=3
      - AUTHELIA_REGULATION_FIND_TIME=10m
      - AUTHELIA_REGULATION_BAN_TIME=12h
      - AUTHELIA_STORAGE_LOCAL_PATH=/config/db.sqlite3
      - AUTHELIA_NOTIFIER_DISABLE_STARTUP_CHECK=false
      - AUTHELIA_NOTIFIER_SMTP_ADDRESS=${SMTP_ADDRESS}
      - AUTHELIA_NOTIFIER_SMTP_USERNAME=${SMTP_USERNAME}
      - AUTHELIA_NOTIFIER_SMTP_SENDER=${SMTP_SENDER}
      - AUTHELIA_NOTIFIER_SMTP_SUBJECT="{title}"
      - AUTHELIA_NOTIFIER_SMTP_STARTUP_CHECK_ADDRESS=${SMTP_STARTUP_CHECK_ADDRESS}
      - AUTHELIA_NOTIFIER_SMTP_DISABLE_REQUIRE_TLS=${SMTP_DISABLE_REQUIRE_TLS}
      - AUTHELIA_NOTIFIER_SMTP_DISABLE_STARTTLS=${SMTP_DISABLE_STARTTLS}
      - AUTHELIA_NOTIFIER_SMTP_DISABLE_HTML_EMAILS=false
      - AUTHELIA_NOTIFIER_SMTP_TIMEOUT=5s
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/secrets/session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/storage_key
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/secrets/smtp_password
    volumes:
      - /messier/apps/authelia/config:/config
      - /messier/apps/authelia/secrets:/secrets:ro
    ports:
      - "9091:9091/tcp"
    networks:
      virgo:
        ipv4_address: 172.30.0.2
    depends_on:
      - authelia-init-secrets
      - authelia-redis
    restart: unless-stopped

  authelia-redis:
    image: redis:latest
    container_name: authelia-redis
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no", "--maxmemory", "32mb", "--maxmemory-policy", "allkeys-lru"]
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /messier/apps/authelia/redis:/data
    ports:
      - "9092:6379/tcp"
    networks:
      virgo:
        ipv4_address: 172.30.0.6
    restart: unless-stopped

networks:
  virgo:
    external: true
