services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    environment:
      - PUID=1000
      - PGID=100
      - AUTHELIA_THEME=light
      - AUTHELIA_SERVER_ADDRESS=tcp://0.0.0.0:9091/
      - AUTHELIA_SERVER_ASSET_PATH=/config/assets/
      - AUTHELIA_SERVER_BUFFERS_WRITE=8192
      - AUTHELIA_SERVER_BUFFERS_READ=8192
      - AUTHELIA_SERVER_DISABLE_HEALTHCHECK=false
      - AUTHELIA_SERVER_ENDPOINTS_ENABLE_EXPVARS=false
      - AUTHELIA_SERVER_ENDPOINTS_ENABLE_PPROF=false
      - AUTHELIA_LOG_LEVEL=info
      - AUTHELIA_LOG_KEEP_STDOUT=false
      - AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_RESET_DISABLE=false
      - AUTHELIA_AUTHENTICATION_BACKEND_REFRESH_INTERVAL=5m
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH=/config/users.yml
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_WATCH=true
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_ALGORITHM=bcrypt
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_BCRYPT_VARIANT=standard
      - AUTHELIA_AUTHENTICATION_BACKEND_FILE_PASSWORD_BCRYPT_COST=12
    volumes:
      - /messier/apps/authelia/config:/config
    ports:
      - "9091:9091/tcp"
    networks:
      virgo:
        ipv4_address: 172.30.0.2
    depends_on:
      - authelia-redis
    restart: unless-stopped

  authelia-redis:
    image: redis:latest
    container_name: authelia-redis
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no", "--maxmemory", "32mb", "--maxmemory-policy", "allkeys-lru"]
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /messier/apps/authelia/redis:/data
    ports:
      - "9092:6379/tcp"
    networks:
      virgo:
        ipv4_address: 172.30.0.6
    restart: unless-stopped

networks:
  virgo:
    external: true
