version: "3.8"
services:
  authelia:
    image: ghcr.io/authelia/authelia:latest
    container_name: authelia
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /portainer/Files/AppData/Config/authelia:/config
    ports:
      - "9091:9091/tcp"
    networks:
      virgo:
        ipv4_address: 172.30.0.2
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: authelia_redis
    command: ["redis-server", "--appendonly", "no", "--protected-mode", "no", "--maxmemory", "32mb", "--maxmemory-policy", "allkeys-lru"]
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /portainer/Files/AppData/Config/authelia_redis:/data
    ports:
      - "9092:6379/tcp"
    networks:
      virgo:
        ipv4_address: 172.30.0.6
    restart: unless-stopped

networks:
  virgo:
    external: true
