version: "3.8"
services:
  authelia:
    image: ghcr.io/authelia/authelia:master
    container_name: authelia
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /portainer/Files/AppData/Config/authelia:/config
    ports:
      - "9091:9091/tcp"
    networks:
      virgo:
        ipv4_address: 172.30.0.2
    restart: unless-stopped

networks:
  virgo:
    external: true
