version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
    volumes:
      - /portainer/Files/AppData/Config/nextcloud/config:/config
      - ${NEXTCLOUD_DATA_DIR}:/data
    ports:
      - "8443:443/tcp"
    depends_on:
      - nextcloud-db
    restart: unless-stopped
    
  nextcloud-db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: nextcloud-db
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /portainer/Files/AppData/Config/nextcloud/db:/config
    restart: unless-stopped
    
  nextcloud-onlyoffice
    image: onlyoffice/documentserver:latest
    container_name: nextcloud-onlyoffice
    environment:
      - PUID=1000
      - PGID=100
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
    volumes:
      - /portainer/Files/AppData/Config/onlyoffice/logs:/var/log/onlyoffice
      - /portainer/Files/AppData/Config/onlyoffice/data:/var/www/onlyoffice/Data
      - /portainer/Files/AppData/Config/onlyoffice/lib:/var/lib/onlyoffice
      - /portainer/Files/AppData/Config/onlyoffice/db:/var/lib/postgresql
      - /portainer/Files/AppData/Config/onlyoffice/redis:/var/lib/redis
      - /portainer/Files/AppData/Config/onlyoffice/rabbitmq:/var/lib/rabbitmq
      - /portainer/Files/AppData/Config/onlyoffice/fonts-custom:/usr/share/fonts/truetype/custom
    ports:
      - "10080:80/tcp"
    restart: unless-stopped
