version: "3.8"
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    environment:
      - PUID=1000
      - PGID=100
      - DISABLE_IPV6=true
      - INITIAL_ADMIN_EMAIL=${ADMIN_EMAIL}
      - INITIAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - /portainer/Files/AppData/Config/nginx-proxy-manager/data:/data
      - /portainer/Files/AppData/Config/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /portainer/Files/AppData/Config/nginx-proxy-manager/snippets:/snippets:ro
    ports:
      - "80:80/tcp"
      - "81:81/tcp"
      - "443:443/tcp"
    networks:
      virgo:
        ipv4_address: 172.30.0.3
    restart: unless-stopped

networks:
  virgo:
    external: true
