version: "3.5"
services:
  odoo:
    image: "odoo:latest"
    container_name: "odoo"
    user: root
    environment:
      - HOST=odoo-postgres
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - /portainer/Files/AppData/Config/odoo/data:/var/lib/odoo
      - /portainer/Files/AppData/Config/odoo/extra-addons:/mnt/extra-addons
    ports:
      - "8069:8069/tcp"
    depends_on:
      - odoo-postgres
    restart: unless-stopped
  
  odoo-postgres:
    image: "postgres:15"
    container_name: odoo-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - /portainer/Files/AppData/Config/odoo/postgres:/var/lib/postgresql/data
    restart: unless-stopped
