version: "3.9"
services:
  odoo:
    image: "odoo:latest"
    container_name: "odoo"
    user: root
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - /messier/apps/odoo/data:/var/lib/odoo
      - /messier/apps/odoo/config:/etc/odoo
      - /messier/apps/odoo/addons:/mnt/extra-addons
    ports:
      - "8069:8069/tcp"
    depends_on:
      - odoo-db
    restart: unless-stopped
  
  odoo-db:
    image: "postgres:15"
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - /messier/apps/odoo/postgres:/var/lib/postgresql/data
    restart: unless-stopped
