services:
  penpot-frontend:
    image: penpotapp/frontend:latest
    container_name: penpot-frontend
    restart: unless-stopped
    environment:
      - PENPOT_FLAGS=disable-email-verification enable-smtp enable-prepl-server enable-login-with-password
      - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=31457280
      - PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE=367001600
    ports:
      - 5080:8080
    volumes:
      - /messier/apps/penpot/frontend/assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot
    
  penpot-backend:
    image: penpotapp/backend:latest
    container_name: penpot-backend
    restart: unless-stopped
      environment:
      << : [*penpot-flags]
      - PENPOT_PUBLIC_URI=http://localhost:5080
      - PENPOT_FLAGS=disable-email-verification enable-smtp enable-prepl-server enable-login-with-password
      - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=31457280
      - PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE=367001600
      ## Penpot SECRET KEY. It serves as a master key from which other keys for subsystems (eg http sessions, or invitations) are derived.
      ## python3 -c "import secrets; print(secrets.token_urlsafe(64))"
      - PENPOT_SECRET_KEY=7y-gr6m55jq6OgRGd1AZLW81SjJWknVoRNwaRfXg1pLa-C0pR37Rg4eepLC6ROloI_g2eoKuiKckkneMSbMzng
      ## The PREPL host. Mainly used for external programatic access to penpot backend
      ## (example: admin). By default it will listen on `localhost` but if you are going to use
      ## the `admin`, you will need to uncomment this and set the host to `0.0.0.0`.
      #- PENPOT_PREPL_HOST=0.0.0.0
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=false
      #- PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      #- PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      #- PENPOT_SMTP_HOST=penpot-mailcatch
      #- PENPOT_SMTP_PORT=1025
      #- PENPOT_SMTP_USERNAME=
      #- PENPOT_SMTP_PASSWORD=
      #- PENPOT_SMTP_TLS=false
      #- PENPOT_SMTP_SSL=false
    volumes:
      - /messier/apps/penpot/backend/assets:/opt/data/assets
    depends_on:
      penpot-postgres:
        condition: service_healthy
      penpot-redis:
        condition: service_healthy
    networks:
      - penpot

  penpot-exporter:
    image: penpotapp/exporter:latest
    container_name: penpot-exporter
    restart: unless-stopped
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend:8080
      - PENPOT_REDIS_URI=redis://penpot-redis/0
    depends_on:
      penpot-redis:
        condition: service_healthy
    networks:
      - penpot

  penpot-postgres:
    image: postgres:15
    container_name: penpot-postgres
    restart: unless-stopped
    stop_signal: SIGINT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U penpot"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 2s
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
    volumes:
      - /messier/apps/penpot/postgres:/var/lib/postgresql/data
    networks:
      - penpot

  penpot-redis:
    image: redis:7.2
    container_name: penpot-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - penpot

networks:
  penpot:
