version: "3"
services:
  pihole:
    image: aleksanderbl/pihole-unbound:latest
    container_name: pihole
    environment:
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - DNSMASQ_LISTENING=all
      - PIHOLE_DOMAIN=${DOMAIN_NAME}
      - PIHOLE_DNS_=127.0.0.1#5335;127.0.0.1#5335
      - DHCP_ACTIVE=${DHCP_ACTIVE}
      - DHCP_START=${DHCP_START}
      - DHCP_END=${DHCP_END}
      - DHCP_ROUTER=${DHCP_ROUTER}
      - DHCP_rapid_commit=true
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - /portainer/Files/AppData/Config/pihole/:/etc/pihole/
      - /portainer/Files/AppData/Config/pihole-logs/pihole:/var/log/pihole
      - /portainer/Files/AppData/Config/pihole-logs/lighttpd:/var/log/lighttpd
      - /portainer/Files/AppData/Config/pihole-dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - "${FTLCONF_LOCAL_IPV4}:53:53/tcp"
      - "${FTLCONF_LOCAL_IPV4}:53:53/udp"
      - "5335:5335/tcp"
      - "8080:80/tcp"
    depends_on:
      - dhcphelper
    dns:
      - 127.0.0.1
    networks:
      virgo:
        ipv4_address: 172.30.0.4
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  dhcphelper:
    container_name: dhcphelper
    image: homeall/dhcphelper:latest
    network_mode: host
    environment:
      IP: 172.30.0.4
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  virgo:
    external: true
