services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    environment:
      - PUID=1000
      - PGID=100
      - DISABLE_IPV6=true
      - INITIAL_ADMIN_EMAIL=${EMAIL}
      - INITIAL_ADMIN_PASSWORD=${PASSWORD}
    volumes:
      - /messier/apps/nginx-proxy-manager/data:/data
      - /messier/apps/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /messier/apps/nginx-proxy-manager/snippets:/snippets:ro
    ports:
      - 80:80/tcp
      - 81:81/tcp
      - 443:443/tcp
    networks:
      virgo:
        ipv4_address: 172.30.0.3
    restart: unless-stopped

networks:
  virgo:
    external: true
